// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LamDT_SE172525.BOs;

public partial class BranchAccount
{
    public int AccountId { get; set; }

    public string AccountPassword { get; set; }

    public string FullName { get; set; }

    public string EmailAddress { get; set; }

    public int? Role { get; set; }
}